### ISSUE TITLE
秘钥派生方法deriveChild的里的PubKey是64字节时报错，只支持33字节的压缩形式。

### ISSUE THREAD

**Issue by limingxie** [WeBankBlockchain/Governance-Key#30]
/Governance-Key/key-core/src/main/java/com/webank/keygen/hd/bip32/ExtendedPrivateKey.java 的
public ExtendedPrivateKey deriveChild(int childIdx) 方法中pubKey只支持33字节的pubkey

```java
else {
            indexBuffer.put(this.eccOperations.compress(publicKey.getPublicKey()));
        }
// =>

// Governance-Key/key-core/src/main/java/com/webank/keygen/crypto/EccOperations.java
// 这里的decodePoint的参数point 只支持33字节的压缩形式。
public byte[] compress(byte[] point) {
        ECPoint ecPoint = CURVE.getCurve().decodePoint(point);
        return ecPoint.getEncoded(true);
}

```

因为现在大部分情况pubKey都是64字节无压缩形式，官网的那些例子也都生成64字节的无压缩形式。
因此官方文档的例子的 
```java
//私钥派生子私钥
ExtendedPrivateKey subPrivKey = rootKey.deriveChild(2);
```
这部分报错,
https://governance-doc.readthedocs.io/zh-cn/latest/docs/WeBankBlockchain-Governance-Key/corequickstart.html#id8

感觉加个判断 64字节和33字节分别处理会好点~

**Comment by wangyue168git** [comment]
[deriveChild _fix](https://github.com/WeBankBlockchain/Governance-Key/pull/31)
